### ISSUE TITLE
README plot images don't render on pypi or in local IDE (pycharm here)

### ISSUE THREAD

**Issue by thorwhalen** [otosense/oplot#2]
For example, on [pypi version 0.0.2](https://pypi.org/project/oplot/0.0.2/), the first multiplot.py image shows up as:

![image](https://user-images.githubusercontent.com/1906276/127305958-c3d5b82d-9d27-4be7-bbec-c94706af2e9f.png)

In the README.md, the image is referenced as:

```
<img src="readme_plots/Screen_Shot_2021-01-06_at_06.23.21.png" width="300">
```

This works for github, but IDE and pypi don't know what do do with this relative reference. 

# What's the best practice for this?

I don't know what the best practice is for this. It seems like a good thing to have a readme_plots folder that is referenced, 
and also a good thing to use relative references. But how to make it work?

Of course, one could get a url for the file (permalink, or url to "raw" data of that file), and use that. 
But that seems like too much work. Perhaps the fallback solution is the best bang for the buck

# My fallback solution

This is how I solved the problem. It has one great advantage; it's a good bang for the buck.

I take a snapshot of the image I want, then copy paste in **any issue or comment of github, anywhere**. 
This results in the image being uploaded to some permanent place, and a url to that place being written in the text area you pasted this in. For the aforementioned `multiplot.py` image, this produced the text
```
![image](https://user-images.githubusercontent.com/1906276/127305797-948851fa-6cb0-4d19-aac1-6508ee7db04f.png)
```
which, when placed in an md rendered (like this issue!) gives us:
![image](https://user-images.githubusercontent.com/1906276/127305797-948851fa-6cb0-4d19-aac1-6508ee7db04f.png)

I've replaced the `<img src="readme_plots/Screen_Shot_2021-01-06_at_06.23.21.png" width="300">` reference of `0.0.2` by this in `0.0.3`, but should do this for all other images.

## More about fallback

After publishing 0.0.3, I saw that the plots were quite big. [See it here](https://pypi.org/project/oplot/0.0.3).

So I'm publishing 0.0.4 now, where instead of 

```
![image](IMAGE_URL)
```

I use 

```
<img src="IMAGE_URL" width="320">
```

to be able to control the size.

It's an extra step that might lead to erratas though, and I see some echoes about how including HTML in md is not stable... 

But it's the best I got for now.

**Comment by cavart28** [comment]
In pycharm, the syntax 
`![](path_to_pic.png)`
 will render the picture, but it is not 
clear how to change the size with this syntax. 

There is a (paid) extension which seems to solve the problem in pycharm (10 bucks a year):
https://plugins.jetbrains.com/plugin/7896-markdown-navigator-enhanced/pricing

I have not tested whether the images shows on pypi/github....

There is also some element of answer here:
https://youtrack.jetbrains.com/issue/IDEA-168607?_ga=2.1744753.1155280612.1627473422-1126975348.1625165379&_gac=1.261295871.1625165459.CjwKCAjwz_WGBhA1EiwAUAxIcSHcE879gz68IRdI0XTJa3R9lyRN4CjKnSVwKhBWiezzEhWDsPxWShoCJzUQAvD_BwE

A related extension allows to copy/paste picture in pycharm markdown:
https://plugins.jetbrains.com/plugin/8446-paste-images-into-markdown

Sylvain's permalink solution seems to work, example of syntax (note that you need to replace BLOB by RAW):
`<img src="https://github.com/otosense/oplot/raw/6295635f4f53d0f588355c3990a8902f34d1a527/readme_plots/Screen%20Shot%202021-01-06%20at%2007.21.26.png">`
To get the permalink, click on the picture on github and then click the three horizontal bars to get the "copy permalink"
